# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: k8s.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'k8s.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tk8s.proto\x12\x03k8s\"/\n\x1f\x43reateDockerContainerPodRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"0\n CreateDockerContainerPodResponse\x12\x0c\n\x04mess\x18\x01 \x01(\t2r\n\x03K8s\x12k\n\x18\x43reateDockerContainerPod\x12$.k8s.CreateDockerContainerPodRequest\x1a%.k8s.CreateDockerContainerPodResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'k8s_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEDOCKERCONTAINERPODREQUEST']._serialized_start=18
  _globals['_CREATEDOCKERCONTAINERPODREQUEST']._serialized_end=65
  _globals['_CREATEDOCKERCONTAINERPODRESPONSE']._serialized_start=67
  _globals['_CREATEDOCKERCONTAINERPODRESPONSE']._serialized_end=115
  _globals['_K8S']._serialized_start=117
  _globals['_K8S']._serialized_end=231
# @@protoc_insertion_point(module_scope)
